#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import time

from Cheese.cheese import CheeseBurger
from Cheese.appSettings import Settings

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if __name__ == "__main__":
    CheeseBurger.init()

    while True:
        try:
            req = {
                "name": Settings.name,
                "port": Settings.port,
                "icon": "/images/icon256.png",
                "color": "FF0000"
            }
            requests.post(f"http://localhost/services/doYouKnowMe", json=req)
            break
        except:
            time.sleep(1)

    CheeseBurger.serveForever()